### ISSUE TITLE
population structure question

### ISSUE THREAD

**Issue by conniecl** [jdrhyne2/FastLORS#1]
Hi, @jdrhyne2 
  I want to us FastLORS to do eQTL mapping in plants, after checking the code and the paper about FastLORS and LORS, I found there are no parameters that can control the population structure(the genotype  derive at least 3 from population)? It's that true? Or there are anything I have missed? Hope can get your response. And how can I integrate the population in eQTL mapping using FastLORS? Sincerely hope can get your advise. And thanks in advance.

**Comment by jdrhyne2** [comment]
Hi @conniecl 

Thank you for your interest in FastLORS.  You are correct that LORS (and therefore FastLORS) does not include parameters to control the population structure.  I discussed this with my mentor and one option is to first fit a model with the expression values and the population structure and then use the residuals as the response matrix in FastLORS, or if P is your matrix for population structure,

```r{echo = FALSE, message = FALSE}
fit <- lm(Y~P)
resids <- fit$residuals
FL <- Run_LORS(Y = resids, X)
```

Hope this helps,

Jacob
